### ISSUE TITLE
PHP-CS-Fixerを利用してPHPフォーマットを統一する

### ISSUE THREAD

**Issue by ynaka6** [tomo778/laravel_spa#6]
チーム開発に向けてコードフォーマットを適応するようにしましょう。
開発者によってフォーマットが異なると可読性が下がる為です。
案件や作業環境によっては、それぞれの開発者が別のIDEを使っていたりします。

個人的には、github actionsなどCIでフォーマットをかけても統一するのが良いと思います。
私は以下のようにPRした時にformatするようにしてます
（参考にしてたサイトを見失ってしまって。。。他の探してURL記載します。
```
name: Format (PHP)

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: composer install

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix ./app

      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply php-cs-fixer changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### [参考URL]
https://qiita.com/suin/items/4242aec018d086312fe7
https://note.com/dafujii/n/n1e52a860c6fa
